### ISSUE TITLE
Can't compile on ubuntu 18.04

### ISSUE THREAD

**Issue by naren-nallapareddy** [kul-forbes/scs#34]
I tried make in ubuntu 18.04, I get error

> 
>  include/util_time.h:6:19: error: field ‘tic’ has incomplete type
>    struct timespec tic;
>                    ^~~
> include/util_time.h:7:19: error: field ‘toc’ has incomplete type
>    struct timespec toc;

It seems I am not able to use struct timespec, I converted it into timeval and it works. Is there a reason timespec doesn't work in ubuntu?

**Comment by naren-nallapareddy** [comment]
Also I get 3 errors when I run 'make run-test'

> <FAIL>  (Test SuperSCS (0,0,1) with FPR) -- y should be nan

> <FAIL>  (Test SuperSCS (0,0,1) with R-Broyden) -- y should be nan

> <FAIL>  (Test residuals) -- rel gap [0] not NAN

**Comment by kunyuan827** [comment]
I got the same error when using Ubuntu 18.04. Any suggestions? Many thanks!

**Comment by kunyuan827** [comment]
> Also I get 3 errors when I run 'make run-test'
> 
> > (Test SuperSCS (0,0,1) with FPR) -- y should be nan
> 
> > (Test SuperSCS (0,0,1) with R-Broyden) -- y should be nan
> 
> > (Test residuals) -- rel gap [0] not NAN

Hi naren3491, did you figure out how to solve these errors?

**Comment by alphaville** [comment]
Hi @naren3491 and @kunyuan827. Sorry for the late reply, I was out of office for a few days. This issue must be related to issue #29. You can certainly ignore the failing tests - the issue is related with the tests themselves rather that the code of SuperSCS.

I had started the branch `fix/xenial`, but I then had to shift my priorities, but I'll try to fix this soon.

**Comment by naren-nallapareddy** [comment]
Hi @alphaville , Thanks for your reply. 

"You can certainly ignore the failing tests - the issue is related with the tests themselves rather that the code of SuperSCS." Thanks for clarifying! That helps. 

Regards, 
Naren

**Comment by kunyuan827** [comment]
> Hi @naren3491 and @kunyuan827. Sorry for the late reply, I was out of office for a few days. This issue must be related to issue #29. You can certainly ignore the failing tests - the issue is related with the tests themselves rather that the code of SuperSCS.
> 
> I had started the branch `fix/xenial`, but I then had to shift my priorities, but I'll try to fix this soon.

Hi @alphaville , thanks for your reply. You're right. I ignored the test errors and the code works well until now.

**Comment by Ununnilium** [comment]
I had the same problem with Debian 10. I could compile it with simply removing `-std=c99` in scs.mk at line 53.

**Comment by hankyang94** [comment]
> I tried make in ubuntu 18.04, I get error
> 
> > include/util_time.h:6:19: error: field ‘tic’ has incomplete type
> > struct timespec tic;
> > ^~~
> > include/util_time.h:7:19: error: field ‘toc’ has incomplete type
> > struct timespec toc;
> 
> It seems I am not able to use struct timespec, I converted it into timeval and it works. Is there a reason timespec doesn't work in ubuntu?

Can you share a working script that shows how to convert timespec into timeval? I am not very familiar with C++.
